# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170919_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Animal'),
        ),
    ]
